apiVersion: content.hauler.cattle.io/v1alpha1
kind: Files
metadata:
  name: rancher-airgap-files-k3s
spec:
  files:
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s-airgap-images-amd64.tar.zst
      name: k3s-airgap-images-amd64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s-airgap-images-amd64.tar.gz
      name: k3s-airgap-images-amd64.tar.gz
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/sha256sum-amd64.txt
      name: sha256sum-amd64.txt
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s
      name: k3s
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s-airgap-images-arm64.tar.zst
      name: k3s-airgap-images-arm64.tar.zst
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s-airgap-images-arm64.tar.gz
      name: k3s-airgap-images-arm64.tar.gz
    - path: https://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/sha256sum-arm64.txt
      name: sha256sum-arm64.txt
    - path: hhttps://github.com/k3s-io/k3s/releases/download/v1.27.10%2Bk3s2/k3s-arm64
      name: k3s-arm64
    - path: https://get.k3s.io
      name: install.sh
    - path: https://github.com/k3s-io/k3s-selinux/releases/download/v1.4.stable.1/k3s-selinux-1.4-1.el8.noarch.rpm
      name: k3s-selinux-1.4-1.el8.noarch.rpm

---
apiVersion: content.hauler.cattle.io/v1alpha1
kind: Images
metadata:
  name: rancher-airgap-images-k3s
spec:
  images:
    - name: docker.io/rancher/klipper-helm:v0.8.2-build20230815
    - name: docker.io/rancher/klipper-lb:v0.4.5
    - name: docker.io/rancher/local-path-provisioner:v0.0.24
    - name: docker.io/rancher/mirrored-coredns-coredns:1.10.1
    - name: docker.io/rancher/mirrored-library-busybox:1.36.1
    - name: docker.io/rancher/mirrored-library-traefik:2.10.5
    - name: docker.io/rancher/mirrored-metrics-server:v0.6.3
    - name: docker.io/rancher/mirrored-pause:3.6
